version: "3.8"
services:
  web:
    image: ghcr.io/ancamna/assignment3-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
